package info.skyblond.daapu.agent.persona

import info.skyblond.daapu.testutil.DbTestBase
import info.skyblond.daapu.testutil.TestDb
import kotlinx.coroutines.runBlocking
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * DB-backed tests for [PostgresPersonaStore] against the throwaway
 * testcontainers PostgreSQL (`testutil/TestDb.kt`): CRUD round trips, id
 * ordering, and the `allowed_namespaces` JSON column round trip.
 */
class PostgresPersonaStoreTest : DbTestBase() {
    private val store = PostgresPersonaStore()

    @Test
    fun `create, find, list, update, delete round trip`() = runBlocking {
        assertTrue(store.list().isEmpty(), "a fresh store lists nothing")

        val created = store.create("coder", "you write code", listOf("fs", "eltm"))
        assertTrue(created.id > 0, "the BIGSERIAL id is generated by the DB")
        assertEquals("coder", created.name)
        assertEquals(listOf("fs", "eltm"), created.allowedNamespaces)

        val loaded = store.findById(created.id)
        assertEquals(created, loaded)

        val listed = store.list()
        assertEquals(listOf(created), listed)

        val updated = store.update(created.id, "coder2", "you write better code", emptyList())
        assertEquals(created.id, updated?.id)
        assertEquals("coder2", updated?.name)
        assertEquals(emptyList(), updated?.allowedNamespaces)
        assertEquals(updated, store.findById(created.id))

        assertTrue(store.delete(created.id))
        assertNull(store.findById(created.id))
        assertFalse(store.delete(created.id), "a second delete finds no row")
        assertTrue(store.list().isEmpty())
    }

    @Test
    fun `list is ordered by id ascending`() = runBlocking {
        val first = store.create("a", "a", emptyList())
        val second = store.create("b", "b", emptyList())
        assertEquals(listOf(first.id, second.id), store.list().map { it.id })
    }

    @Test
    fun `allowed namespaces round trip through the JSON column`() = runBlocking {
        val namespaces = listOf("mcp__exa", "fs", "gsg")
        val created = store.create("multi", "p", namespaces)
        assertEquals(namespaces, store.findById(created.id)?.allowedNamespaces)
    }

    @Test
    fun `update returns null for a missing id`() = runBlocking {
        assertNull(store.update(4242L, "x", "y", emptyList()))
    }

    @Test
    fun `resetAll restarts the BIGSERIAL identity for deterministic ids`() = runBlocking {
        store.create("a", "a", emptyList())
        TestDb.resetAll()
        val second = store.create("b", "b", emptyList())
        assertEquals(
            1L, second.id,
            "TRUNCATE ... RESTART IDENTITY restarts the sequence: ids stay deterministic " +
                    "across tests (seeded rows can be addressed by id)",
        )
    }
}
