package info.skyblond.daapu.llm

import ai.koog.agents.chatMemory.feature.ChatHistoryProvider
import ai.koog.prompt.message.Message
import info.skyblond.daapu.db.Chats
import info.skyblond.daapu.db.newChatId
import info.skyblond.daapu.db.withTransaction
import kotlinx.serialization.json.Json
import org.jetbrains.exposed.v1.core.eq
import org.jetbrains.exposed.v1.jdbc.selectAll
import org.jetbrains.exposed.v1.jdbc.upsert

/**
 * Postgres-backed [ChatHistoryProvider] for koog's `ChatMemory` feature.
 *
 * koog owns the conversation history: it loads the full history before each run
 * and stores the full updated history after the run completes. The whole
 * [Message] list is serialized into the chat row's `history_json` column as one
 * JSON array, so a chat's history is loaded and stored as a single row.
 *
 * [ChatHistoryProvider.load] and [ChatHistoryProvider.store] receive koog's
 * opaque conversation id; it is exactly the chat id string generated by
 * [newChatId], used verbatim as the `chats.id` primary key.
 */
class PostgresChatHistoryProvider : ChatHistoryProvider {

    private val json = Json {
        ignoreUnknownKeys = true
        explicitNulls = false
    }

    override suspend fun load(conversationId: String): List<Message> = withTransaction {
        val historyJson = Chats.selectAll()
            .where { Chats.id eq conversationId }
            .singleOrNull()
            ?.get(Chats.historyJson)
            ?: return@withTransaction emptyList()
        json.decodeFromString(historyJson)
    }

    override suspend fun store(conversationId: String, messages: List<Message>) {
        val historyJson = json.encodeToString(messages)
        withTransaction {
            Chats.upsert {
                it[Chats.id] = conversationId
                it[Chats.historyJson] = historyJson
            }
        }
    }
}
