package info.skyblond.daapu.db

import org.jetbrains.exposed.v1.core.Table

/**
 * Mirror of the `chats` table created by `V1__init.sql`.
 *
 * koog's ChatMemory owns the conversation history; [historyJson] stores the
 * full serialized koog `Message` list for the chat as one JSON array. The chat
 * id is a snowflake-like string (see [newChatId]) generated by the application,
 * and doubles as koog's opaque conversation id.
 */
object Chats : Table("chats") {
    val id = text("id")
    val historyJson = text("history_json").default("[]")

    override val primaryKey = PrimaryKey(id)
}
