package info.skyblond.daapu.db

import org.jetbrains.exposed.v1.core.Table
import org.jetbrains.exposed.v1.javatime.CurrentTimestamp
import org.jetbrains.exposed.v1.javatime.timestamp

/**
 * Mirror of the `chats` table created by `V1__init.sql`.
 *
 * The conversation history is stored in [historyJson] as the project-owned
 * framework-neutral format (see `history/HistoryMessage.kt`): one JSON array
 * per chat, with no framework type names. The turn loop
 * (`agent/ChatTurnLoop.kt`) loads the full history before a run and stores
 * the full updated history after a successful run via
 * `history/PostgresHistoryStore.kt`. The chat id is a snowflake-like string
 * (see [newChatId]) generated by the application.
 */
object Chats : Table("chats") {
    val id = text("id")
    val historyJson = text("history_json").default("[]")

    override val primaryKey = PrimaryKey(id)
}

/**
 * Shared Short Term Memories.
 */
object SSTMs : Table("sstms") {
    val id = long("id").autoIncrement()
    val lastUpdate = timestamp("last_update")
        .defaultExpression(CurrentTimestamp)
    val content = text("content")

    override val primaryKey = PrimaryKey(id)
}